// SHADERS
#define BASESHADER_FRAG         1001
#define BASESHADER_VERT         1002
#define STANDARDSHADER_VERT     1004
#define STANDARDSHADER_FRAG     1005
#define FONTSHADER_FRAG         1007
#define FONTSHADER_VERT         1008
#define PHONGSHADER_FRAG        1010
#define PHONGSHADER_VERT        1011
#define WIREFRAMESHADER_FRAG    1013
#define WIREFRAMESHADER_VERT    1014
#define PARTICLESSHADER_VERT    1016
#define PARTICLESSHADER_FRAG    1017
#define PARTICLESSHADER_GEOM    1018

// BITMAPS
#define IMG_AVATAR              2000

// FONTS
#define FONT_CONSOLAS           3000

// CONFIG
#ifndef CONFIG_ENGINE
	#define CONFIG_ENGINE           5000
#endif
